/**
 * PLACEHOLDER / DEMO DATA ONLY.
 *
 * Nothing in this file represents a trained model, a measured benchmark score,
 * or live infrastructure telemetry. Every metric that would require a real
 * backend is `null` and is rendered by the UI as "Not connected" /
 * "Awaiting backend" / "Placeholder". This module is isolated from the rest of
 * the app behind the LabApi interface so it can be deleted once real services
 * exist.
 */

import type {
  ActivityEntry,
  Alert,
  ApiKeyRecord,
  AuditLogEntry,
  Benchmark,
  ComputeNode,
  ComputeSummary,
  DatasetRecord,
  DocPage,
  EvaluationRun,
  Experiment,
  Milestone,
  ModelRecord,
  Paper,
  PipelineStage,
  Program,
  ResearchProject,
  ResearchQuestion,
  RoadmapPhase,
  TeamMember,
  TrainingRun,
} from "./types";

export const INDIAN_LANGUAGES = [
  "English",
  "Hindi",
  "Hinglish",
  "Bengali",
  "Tamil",
  "Telugu",
  "Marathi",
  "Gujarati",
  "Kannada",
  "Malayalam",
  "Punjabi",
  "Odia",
  "Assamese",
  "Urdu",
];

export const program: Program = {
  id: "prog-001",
  project: "PROJECT 001 — BHARAT FOUNDATION",
  phase: "Architecture + tokenizer research",
  currentModel: "Bharat-50M",
  status: "Research",
  training: "not_started",
  latestBenchmark: null,
};

export const researchProjects: ResearchProject[] = [
  {
    id: "RP-001",
    title: "Tokenizer strategy for Indian-language corpora",
    objective:
      "Determine a tokenizer design that keeps fertility low across Devanagari, Dravidian and Perso-Arabic scripts without inflating vocabulary cost.",
    hypothesis:
      "A byte-level BPE with script-aware pre-tokenisation reduces tokens-per-word for Indic scripts versus a naive multilingual BPE.",
    owner: "Research lead",
    status: "active",
    priority: "P0",
    createdAt: "2026-01-12",
    experimentIds: ["EXP-0006"],
    datasetIds: ["DS-002", "DS-003"],
    modelIds: ["M-050M"],
    findings: ["No measured findings yet — experiments not executed."],
    decisions: ["Vocabulary sweep to cover 32k / 64k / 128k before architecture freeze."],
    notes: "Placeholder record.",
  },
  {
    id: "RP-002",
    title: "Small-scale Transformer architecture ablations",
    objective:
      "Establish a stable 50M-parameter reference architecture that scales predictably to 300M and 1B.",
    hypothesis:
      "Pre-norm + RoPE + SwiGLU gives the most stable loss curve at small scale under limited compute.",
    owner: "Research lead",
    status: "active",
    priority: "P0",
    createdAt: "2026-01-20",
    experimentIds: ["EXP-0004", "EXP-0007"],
    datasetIds: ["DS-001"],
    modelIds: ["M-050M", "M-100M"],
    findings: ["Awaiting backend — no runs executed."],
    decisions: ["Architecture frozen only after tokenizer v1."],
    notes: "Placeholder record.",
  },
  {
    id: "RP-003",
    title: "Data provenance and licensing framework",
    objective:
      "Define an auditable provenance record for every corpus entering the pretraining mixture.",
    hypothesis:
      "Provenance recorded at ingestion is cheaper than retro-auditing a mixed corpus.",
    owner: "Data engineering",
    status: "open",
    priority: "P1",
    createdAt: "2026-02-02",
    experimentIds: [],
    datasetIds: ["DS-001", "DS-002", "DS-003", "DS-004"],
    modelIds: [],
    findings: [],
    decisions: ["No corpus enters the mixture without a licence classification."],
    notes: "Placeholder record.",
  },
  {
    id: "RP-004",
    title: "Evaluation design for Indian knowledge and code-mixing",
    objective: "Specify the first internal benchmark suite under BHARAT EVAL.",
    hypothesis:
      "Existing English benchmarks under-measure Indic capability; code-mixed evaluation is required.",
    owner: "Evaluation",
    status: "open",
    priority: "P1",
    createdAt: "2026-02-14",
    experimentIds: [],
    datasetIds: [],
    modelIds: [],
    findings: [],
    decisions: [],
    notes: "Placeholder record.",
  },
];

export const researchQuestions: ResearchQuestion[] = [
  {
    id: "RQ-01",
    question: "What vocabulary size minimises Indic fertility at acceptable embedding cost?",
    area: "Tokenizer",
    status: "active",
    owner: "Research lead",
  },
  {
    id: "RQ-02",
    question: "Does script-aware pre-tokenisation help or hurt code-mixed Hinglish?",
    area: "Tokenizer",
    status: "open",
    owner: "Research lead",
  },
  {
    id: "RQ-03",
    question: "Which small-scale architecture choices transfer reliably to 1B+?",
    area: "Architecture",
    status: "active",
    owner: "Research lead",
  },
  {
    id: "RQ-04",
    question: "What is the minimum viable deduplication strategy for Indic web text?",
    area: "Data",
    status: "open",
    owner: "Data engineering",
  },
  {
    id: "RQ-05",
    question: "How do we detect benchmark contamination in scraped Indic corpora?",
    area: "Evaluation",
    status: "open",
    owner: "Evaluation",
  },
];

export const openProblems = [
  "No measured scaling law for Indic-heavy mixtures at small scale.",
  "Licensing status of large parts of the Indic web is unresolved.",
  "No public high-quality evaluation set for Indian legal or medical reasoning.",
  "Compute backend not selected — no cluster commitments yet.",
];

export const papers: Paper[] = [
  {
    id: "P-01",
    title: "Attention Is All You Need",
    authors: "Vaswani et al.",
    year: 2017,
    relevance: "Baseline architecture reference.",
    status: "read",
  },
  {
    id: "P-02",
    title: "Neural Machine Translation of Rare Words with Subword Units",
    authors: "Sennrich et al.",
    year: 2016,
    relevance: "BPE tokenizer foundation.",
    status: "read",
  },
  {
    id: "P-03",
    title: "Training Compute-Optimal Large Language Models",
    authors: "Hoffmann et al.",
    year: 2022,
    relevance: "Token/parameter budgeting for the phase plan.",
    status: "reading",
  },
  {
    id: "P-04",
    title: "RoFormer: Enhanced Transformer with Rotary Position Embedding",
    authors: "Su et al.",
    year: 2021,
    relevance: "Positional scheme candidate.",
    status: "to_read",
  },
];

export const models: ModelRecord[] = [
  {
    id: "M-050M",
    name: "Bharat-50M",
    family: "Bharat",
    parameterCount: "≈50M (target)",
    architecture: "Decoder-only Transformer (pre-norm, RoPE, SwiGLU) — proposed",
    tokenizerVersion: "tok-v0.3 (draft)",
    contextLength: 2048,
    trainingDatasetVersion: null,
    trainingTokens: null,
    trainingCompute: null,
    trainingDuration: null,
    checkpointLocation: null,
    status: "in_research",
    evaluationVersion: null,
    license: "Internal — undecided",
    parentModelId: null,
    branch: "base",
    createdAt: "2026-01-12",
    researcher: "Research lead",
    notes: "Roadmap placeholder. Not trained.",
  },
  {
    id: "M-100M",
    name: "Bharat-100M",
    family: "Bharat",
    parameterCount: "≈100M (target)",
    architecture: "Inherits 50M reference architecture — proposed",
    tokenizerVersion: "tok-v1 (planned)",
    contextLength: 2048,
    trainingDatasetVersion: null,
    trainingTokens: null,
    trainingCompute: null,
    trainingDuration: null,
    checkpointLocation: null,
    status: "roadmap",
    evaluationVersion: null,
    license: "Internal — undecided",
    parentModelId: "M-050M",
    branch: "base",
    createdAt: "2026-01-12",
    researcher: "Research lead",
    notes: "Roadmap placeholder. Not trained.",
  },
  {
    id: "M-300M",
    name: "Bharat-300M",
    family: "Bharat",
    parameterCount: "≈300M (target)",
    architecture: "Proposed",
    tokenizerVersion: "tok-v1 (planned)",
    contextLength: 4096,
    trainingDatasetVersion: null,
    trainingTokens: null,
    trainingCompute: null,
    trainingDuration: null,
    checkpointLocation: null,
    status: "roadmap",
    evaluationVersion: null,
    license: "Internal — undecided",
    parentModelId: "M-100M",
    branch: "base",
    createdAt: "2026-01-12",
    researcher: "Research lead",
    notes: "Roadmap placeholder. Not trained.",
  },
  {
    id: "M-1B",
    name: "Bharat-1B",
    family: "Bharat",
    parameterCount: "≈1B (target)",
    architecture: "Proposed",
    tokenizerVersion: "tok-v1 (planned)",
    contextLength: 4096,
    trainingDatasetVersion: null,
    trainingTokens: null,
    trainingCompute: null,
    trainingDuration: null,
    checkpointLocation: null,
    status: "roadmap",
    evaluationVersion: null,
    license: "Internal — undecided",
    parentModelId: "M-300M",
    branch: "base",
    createdAt: "2026-01-12",
    researcher: "Research lead",
    notes: "Roadmap placeholder. Not trained.",
  },
  {
    id: "M-3B",
    name: "Bharat-3B",
    family: "Bharat",
    parameterCount: "≈3B (target)",
    architecture: "Proposed",
    tokenizerVersion: "tok-v2 (planned)",
    contextLength: 8192,
    trainingDatasetVersion: null,
    trainingTokens: null,
    trainingCompute: null,
    trainingDuration: null,
    checkpointLocation: null,
    status: "roadmap",
    evaluationVersion: null,
    license: "Internal — undecided",
    parentModelId: "M-1B",
    branch: "base",
    createdAt: "2026-01-12",
    researcher: "Research lead",
    notes: "Roadmap placeholder. Not trained.",
  },
  {
    id: "M-7B",
    name: "Bharat-7B",
    family: "Bharat",
    parameterCount: "≈7B (target)",
    architecture: "Proposed",
    tokenizerVersion: "tok-v2 (planned)",
    contextLength: 8192,
    trainingDatasetVersion: null,
    trainingTokens: null,
    trainingCompute: null,
    trainingDuration: null,
    checkpointLocation: null,
    status: "roadmap",
    evaluationVersion: null,
    license: "Internal — undecided",
    parentModelId: "M-3B",
    branch: "base",
    createdAt: "2026-01-12",
    researcher: "Research lead",
    notes: "Roadmap placeholder. Not trained.",
  },
  {
    id: "M-14B",
    name: "Bharat-14B",
    family: "Bharat",
    parameterCount: "≈14B (target)",
    architecture: "Proposed",
    tokenizerVersion: "tok-v2 (planned)",
    contextLength: 16384,
    trainingDatasetVersion: null,
    trainingTokens: null,
    trainingCompute: null,
    trainingDuration: null,
    checkpointLocation: null,
    status: "roadmap",
    evaluationVersion: null,
    license: "Internal — undecided",
    parentModelId: "M-7B",
    branch: "base",
    createdAt: "2026-01-12",
    researcher: "Research lead",
    notes: "Roadmap placeholder. Not trained.",
  },
  {
    id: "M-R1",
    name: "Bharat-R (reasoning)",
    family: "Bharat",
    parameterCount: "TBD",
    architecture: "Post-trained reasoning branch — proposed",
    tokenizerVersion: "inherits base",
    contextLength: null,
    trainingDatasetVersion: null,
    trainingTokens: null,
    trainingCompute: null,
    trainingDuration: null,
    checkpointLocation: null,
    status: "roadmap",
    evaluationVersion: null,
    license: "Internal — undecided",
    parentModelId: "M-7B",
    branch: "reasoning",
    createdAt: "2026-01-12",
    researcher: "Research lead",
    notes: "Roadmap placeholder. Not trained.",
  },
  {
    id: "M-V1",
    name: "Bharat-V (vision)",
    family: "Bharat",
    parameterCount: "TBD",
    architecture: "Vision adapter branch — proposed",
    tokenizerVersion: "inherits base",
    contextLength: null,
    trainingDatasetVersion: null,
    trainingTokens: null,
    trainingCompute: null,
    trainingDuration: null,
    checkpointLocation: null,
    status: "roadmap",
    evaluationVersion: null,
    license: "Internal — undecided",
    parentModelId: "M-7B",
    branch: "vision",
    createdAt: "2026-01-12",
    researcher: "Research lead",
    notes: "Roadmap placeholder. Not trained.",
  },
  {
    id: "M-S1",
    name: "Bharat-S (speech)",
    family: "Bharat",
    parameterCount: "TBD",
    architecture: "Speech branch — proposed",
    tokenizerVersion: "TBD",
    contextLength: null,
    trainingDatasetVersion: null,
    trainingTokens: null,
    trainingCompute: null,
    trainingDuration: null,
    checkpointLocation: null,
    status: "roadmap",
    evaluationVersion: null,
    license: "Internal — undecided",
    parentModelId: "M-7B",
    branch: "speech",
    createdAt: "2026-01-12",
    researcher: "Research lead",
    notes: "Roadmap placeholder. Not trained.",
  },
  {
    id: "M-MM1",
    name: "Bharat-MM (multimodal)",
    family: "Bharat",
    parameterCount: "TBD",
    architecture: "Multimodal fusion branch — proposed",
    tokenizerVersion: "TBD",
    contextLength: null,
    trainingDatasetVersion: null,
    trainingTokens: null,
    trainingCompute: null,
    trainingDuration: null,
    checkpointLocation: null,
    status: "roadmap",
    evaluationVersion: null,
    license: "Internal — undecided",
    parentModelId: "M-14B",
    branch: "multimodal",
    createdAt: "2026-01-12",
    researcher: "Research lead",
    notes: "Roadmap placeholder. Not trained.",
  },
  {
    id: "M-AG1",
    name: "Bharat-A (agent)",
    family: "Bharat",
    parameterCount: "TBD",
    architecture: "Agentic post-training branch — proposed",
    tokenizerVersion: "inherits base",
    contextLength: null,
    trainingDatasetVersion: null,
    trainingTokens: null,
    trainingCompute: null,
    trainingDuration: null,
    checkpointLocation: null,
    status: "roadmap",
    evaluationVersion: null,
    license: "Internal — undecided",
    parentModelId: "M-14B",
    branch: "agent",
    createdAt: "2026-01-12",
    researcher: "Research lead",
    notes: "Roadmap placeholder. Not trained.",
  },
];

export const experiments: Experiment[] = [
  {
    id: "EXP-0007",
    name: "GELU / SwiGLU activation ablation",
    hypothesis: "SwiGLU improves loss at equal parameter budget on a 50M reference.",
    modelConfig: "50M · 12L · d=512 · 8 heads",
    tokenizer: "tok-v0.3 (draft)",
    datasetVersion: "ds-mix-v0.1 (draft)",
    tokens: null,
    batchSize: 256,
    learningRate: "3e-4",
    optimizer: "AdamW",
    scheduler: "cosine, 2k warmup",
    contextLength: 2048,
    precision: "bf16",
    gpuType: null,
    gpuCount: null,
    duration: null,
    checkpoint: null,
    loss: null,
    validationLoss: null,
    benchmarkResults: null,
    notes: "Configuration drafted. Requires compute backend before execution.",
    researcher: "Research lead",
    status: "PLANNED",
    createdAt: "2026-02-18",
  },
  {
    id: "EXP-0006",
    name: "Hindi tokenizer 128k vocabulary sweep",
    hypothesis: "128k vocabulary lowers Devanagari fertility below 1.6 tokens/word.",
    modelConfig: "n/a — tokenizer only",
    tokenizer: "tok-v0.3 (draft)",
    datasetVersion: "ds-hindi-v0.1",
    tokens: null,
    batchSize: null,
    learningRate: null,
    optimizer: "n/a",
    scheduler: "n/a",
    contextLength: null,
    precision: "n/a",
    gpuType: null,
    gpuCount: null,
    duration: null,
    checkpoint: null,
    loss: null,
    validationLoss: null,
    benchmarkResults: null,
    notes: "Blocked on corpus licensing review.",
    researcher: "Research lead",
    status: "QUEUED",
    createdAt: "2026-02-11",
  },
  {
    id: "EXP-0005",
    name: "Context length 4k sweep",
    hypothesis: "RoPE base scaling holds to 4k without loss degradation at 50M.",
    modelConfig: "50M · 12L · d=512",
    tokenizer: "tok-v0.3 (draft)",
    datasetVersion: "ds-mix-v0.1 (draft)",
    tokens: null,
    batchSize: 128,
    learningRate: "3e-4",
    optimizer: "AdamW",
    scheduler: "cosine",
    contextLength: 4096,
    precision: "bf16",
    gpuType: null,
    gpuCount: null,
    duration: null,
    checkpoint: null,
    loss: null,
    validationLoss: null,
    benchmarkResults: null,
    notes: "Awaiting backend.",
    researcher: "Research lead",
    status: "PLANNED",
    createdAt: "2026-02-05",
  },
  {
    id: "EXP-0004",
    name: "Tiny Transformer reference implementation",
    hypothesis: "A from-scratch training loop reproduces expected loss on a toy corpus.",
    modelConfig: "≈6M · 6L · d=256",
    tokenizer: "char-level",
    datasetVersion: "toy-v0",
    tokens: null,
    batchSize: 64,
    learningRate: "6e-4",
    optimizer: "AdamW",
    scheduler: "linear",
    contextLength: 256,
    precision: "fp32",
    gpuType: null,
    gpuCount: null,
    duration: null,
    checkpoint: null,
    loss: null,
    validationLoss: null,
    benchmarkResults: null,
    notes: "Learning-phase exercise. Results recorded outside this control plane until backend exists.",
    researcher: "Research lead",
    status: "PLANNED",
    createdAt: "2026-01-28",
  },
  {
    id: "EXP-0003",
    name: "Deduplication strategy dry-run",
    hypothesis: "MinHash LSH at 0.8 Jaccard removes near-duplicates without harming coverage.",
    modelConfig: "n/a — data only",
    tokenizer: "n/a",
    datasetVersion: "ds-web-v0.1",
    tokens: null,
    batchSize: null,
    learningRate: null,
    optimizer: "n/a",
    scheduler: "n/a",
    contextLength: null,
    precision: "n/a",
    gpuType: null,
    gpuCount: null,
    duration: null,
    checkpoint: null,
    loss: null,
    validationLoss: null,
    benchmarkResults: null,
    notes: "Pipeline backend not connected.",
    researcher: "Data engineering",
    status: "PLANNED",
    createdAt: "2026-01-22",
  },
];

export const trainingRuns: TrainingRun[] = [
  {
    id: "RUN-0001",
    experimentId: "EXP-0006",
    name: "tokenizer-sweep-128k",
    status: "queued",
    gpuAllocation: null,
    gpuUtilization: null,
    memoryUtilization: null,
    tokensPerSecond: null,
    estimatedCompletion: null,
    checkpointStatus: null,
    trainingLoss: null,
    validationLoss: null,
    submittedAt: "2026-02-11",
  },
];

export const datasets: DatasetRecord[] = [
  {
    id: "DS-001",
    name: "Indic web crawl (candidate)",
    languages: INDIAN_LANGUAGES,
    domain: "Web",
    source: "Public crawl — candidate",
    licensingStatus: "under_review",
    collectionMethod: "Crawl (not started)",
    size: null,
    tokenCount: null,
    qualityScore: null,
    duplicateRate: null,
    filteringVersion: "filter-v0",
    contaminationStatus: "not_checked",
    piiStatus: "not_checked",
    copyrightStatus: "not_checked",
    documentation: "Draft datasheet",
    owner: "Data engineering",
    version: "v0.1",
    updatedAt: "2026-02-16",
  },
  {
    id: "DS-002",
    name: "Hindi long-form corpus (candidate)",
    languages: ["Hindi", "Hinglish", "English"],
    domain: "News, literature",
    source: "Licensed partners — under discussion",
    licensingStatus: "under_review",
    collectionMethod: "Partner feed (not started)",
    size: null,
    tokenCount: null,
    qualityScore: null,
    duplicateRate: null,
    filteringVersion: "filter-v0",
    contaminationStatus: "not_checked",
    piiStatus: "not_checked",
    copyrightStatus: "not_checked",
    documentation: "Draft datasheet",
    owner: "Data engineering",
    version: "v0.1",
    updatedAt: "2026-02-14",
  },
  {
    id: "DS-003",
    name: "Dravidian language mix (candidate)",
    languages: ["Tamil", "Telugu", "Kannada", "Malayalam"],
    domain: "Mixed",
    source: "Open corpora — candidate",
    licensingStatus: "unknown",
    collectionMethod: "Not started",
    size: null,
    tokenCount: null,
    qualityScore: null,
    duplicateRate: null,
    filteringVersion: "filter-v0",
    contaminationStatus: "not_checked",
    piiStatus: "not_checked",
    copyrightStatus: "not_checked",
    documentation: "Not written",
    owner: "Data engineering",
    version: "v0.1",
    updatedAt: "2026-02-09",
  },
  {
    id: "DS-004",
    name: "Code corpus (candidate)",
    languages: ["English"],
    domain: "Source code",
    source: "Permissively licensed repositories — candidate",
    licensingStatus: "under_review",
    collectionMethod: "Not started",
    size: null,
    tokenCount: null,
    qualityScore: null,
    duplicateRate: null,
    filteringVersion: "filter-v0",
    contaminationStatus: "not_checked",
    piiStatus: "not_checked",
    copyrightStatus: "not_checked",
    documentation: "Draft datasheet",
    owner: "Data engineering",
    version: "v0.1",
    updatedAt: "2026-02-06",
  },
];

export const pipelineStages: PipelineStage[] = [
  "Raw data",
  "Ingestion",
  "Language identification",
  "Quality filtering",
  "Deduplication",
  "PII / safety filtering",
  "License / provenance check",
  "Contamination check",
  "Tokenization",
  "Training dataset",
  "Versioned dataset",
].map((name, i) => ({
  id: `ST-${String(i + 1).padStart(2, "0")}`,
  name,
  status: i === 0 ? "ready" : i === 1 ? "idle" : "not_configured",
  version: i <= 1 ? "v0.1" : "—",
  timestamp: null,
  records: null,
  tokens: null,
  errors: null,
  qualityMetric: null,
}));

export const benchmarkCategories = [
  "Language",
  "Reasoning",
  "Mathematics",
  "Science",
  "Coding",
  "Indian knowledge",
  "Indian culture/context",
  "Education",
  "JEE",
  "NEET",
  "UPSC",
  "Legal reasoning",
  "Medical knowledge",
  "Long context",
  "Instruction following",
  "Safety",
  "Hallucination",
  "Tool use",
  "Agent performance",
  "Multilingual reasoning",
  "Code-mixing",
];

export const benchmarks: Benchmark[] = benchmarkCategories.map((category, i) => ({
  id: `BE-${String(i + 1).padStart(3, "0")}`,
  name: `BHARAT EVAL · ${category}`,
  category,
  languages: i % 3 === 0 ? INDIAN_LANGUAGES : ["English", "Hindi", "Hinglish"],
  version: "v0.1 (draft)",
  items: null,
  evaluationType: category === "Safety" || category === "Agent performance" ? "hybrid" : "automated",
  contaminationChecked: false,
  status: i < 3 ? "authoring" : "draft",
  owner: "Evaluation",
}));

export const evaluationRuns: EvaluationRun[] = [];

export const computeNodes: ComputeNode[] = [
  {
    id: "CN-001",
    label: "Workstation (planned)",
    provider: "Local",
    gpuType: "TBD",
    gpuCount: 1,
    allocated: 0,
    utilization: null,
    vram: null,
    temperature: null,
    power: null,
    status: "planned",
  },
  {
    id: "CN-002",
    label: "Cloud pool (planned)",
    provider: "Provider-agnostic",
    gpuType: "TBD",
    gpuCount: 0,
    allocated: 0,
    utilization: null,
    vram: null,
    temperature: null,
    power: null,
    status: "planned",
  },
];

export const computeSummary: ComputeSummary = {
  backend: "not_connected",
  totalGpus: 0,
  allocatedGpus: 0,
  storage: null,
  network: null,
  estimatedCost: null,
};

export const roadmapPhases: RoadmapPhase[] = [
  {
    id: "PH-0",
    index: 0,
    title: "Company + research infrastructure",
    objective: "Stand up the lab: control plane, conventions, provenance and security posture.",
    prerequisites: ["Team formed", "Working name agreed"],
    researchQuestions: ["What must be reproducible from day one?"],
    engineering: ["Control plane", "Entity versioning", "Audit logging"],
    data: ["Provenance policy"],
    compute: ["None"],
    evaluation: ["Evaluation framework specification"],
    successCriteria: ["Every experiment has an immutable record"],
    risks: ["Process overhead outpacing research output"],
    status: "active",
  },
  {
    id: "PH-1",
    index: 1,
    title: "Learning + tiny Transformer",
    objective: "Implement a Transformer and training loop from scratch on toy data.",
    prerequisites: ["Phase 0"],
    researchQuestions: ["Does our training loop reproduce known baselines?"],
    engineering: ["Reference implementation", "Checkpointing"],
    data: ["Toy corpus"],
    compute: ["Single GPU"],
    evaluation: ["Loss curve sanity checks"],
    successCriteria: ["Reproducible loss on a toy corpus"],
    risks: ["Silent correctness bugs in the loop"],
    status: "planned",
  },
  ...[
    ["Bharat-50M", "50M", 2],
    ["Bharat-100M", "100M", 3],
    ["Bharat-300M", "300M", 4],
    ["Bharat-1B", "1B", 5],
    ["Bharat-3B", "3B", 6],
    ["Bharat-7B+", "7B+", 7],
  ].map(([title, size, index]) => ({
    id: `PH-${index}`,
    index: index as number,
    title: title as string,
    objective: `Pretrain a ${size} parameter base model from randomly initialised weights.`,
    prerequisites: [`Phase ${(index as number) - 1}`, "Tokenizer version frozen", "Dataset version frozen"],
    researchQuestions: ["Do small-scale architecture choices hold at this scale?"],
    engineering: ["Distributed training", "Checkpoint recovery", "Throughput profiling"],
    data: ["Versioned, deduplicated, licence-cleared mixture"],
    compute: ["Cluster allocation — not committed"],
    evaluation: ["BHARAT EVAL regression suite"],
    successCriteria: ["Stable loss curve and no evaluation regression versus prior scale"],
    risks: ["Compute availability", "Data quality ceiling"],
    status: "planned" as const,
  })),
  {
    id: "PH-8",
    index: 8,
    title: "Reasoning",
    objective: "Post-train a reasoning branch on top of the strongest base model.",
    prerequisites: ["Phase 7"],
    researchQuestions: ["Which post-training signal improves Indic reasoning?"],
    engineering: ["Post-training pipeline", "Preference data tooling"],
    data: ["Reasoning traces"],
    compute: ["Cluster allocation"],
    evaluation: ["Reasoning + mathematics suites"],
    successCriteria: ["Measured gains over base on internal reasoning suites"],
    risks: ["Reward hacking", "Evaluation contamination"],
    status: "planned",
  },
  {
    id: "PH-9",
    index: 9,
    title: "Multimodal",
    objective: "Add vision understanding to the model family.",
    prerequisites: ["Phase 8"],
    researchQuestions: ["What fusion approach fits our compute budget?"],
    engineering: ["Vision encoder integration"],
    data: ["Licensed image-text pairs"],
    compute: ["Cluster allocation"],
    evaluation: ["Multimodal suites"],
    successCriteria: ["Baseline multimodal capability measured internally"],
    risks: ["Data licensing"],
    status: "planned",
  },
  {
    id: "PH-10",
    index: 10,
    title: "Speech",
    objective: "Speech recognition and synthesis for Indian languages.",
    prerequisites: ["Phase 9"],
    researchQuestions: ["How much speech data per language is required?"],
    engineering: ["Audio pipeline"],
    data: ["Consented speech corpora"],
    compute: ["Cluster allocation"],
    evaluation: ["Speech suites"],
    successCriteria: ["Measured accuracy across target languages"],
    risks: ["Consent and privacy"],
    status: "planned",
  },
  {
    id: "PH-11",
    index: 11,
    title: "Agents",
    objective: "Tool use and agentic behaviour on top of the reasoning branch.",
    prerequisites: ["Phase 8"],
    researchQuestions: ["How do we evaluate multi-step agent reliability?"],
    engineering: ["Tool interface", "Sandboxed execution"],
    data: ["Trajectory data"],
    compute: ["Inference capacity"],
    evaluation: ["Agent performance suites"],
    successCriteria: ["Reliable multi-step task completion measured internally"],
    risks: ["Safety of autonomous execution"],
    status: "planned",
  },
  {
    id: "PH-12",
    index: 12,
    title: "Frontier-scale training",
    objective: "Train a globally competitive frontier model from India.",
    prerequisites: ["All prior phases"],
    researchQuestions: ["Open"],
    engineering: ["Large distributed cluster operations"],
    data: ["Frontier-scale licensed mixture"],
    compute: ["Large dedicated cluster — not secured"],
    evaluation: ["Full BHARAT EVAL + external benchmarks"],
    successCriteria: ["Competitive on internal and public evaluations"],
    risks: ["Capital", "Compute supply", "Talent"],
    status: "planned",
  },
];

export const milestones: Milestone[] = [
  { id: "MS-1", title: "Control plane v0.1 in use", phase: "Phase 0", target: "Q1", status: "in_progress" },
  { id: "MS-2", title: "Tokenizer v1 frozen", phase: "Phase 0", target: "Q2", status: "planned" },
  { id: "MS-3", title: "Tiny Transformer reproduces baseline", phase: "Phase 1", target: "Q2", status: "planned" },
  { id: "MS-4", title: "First compute backend connected", phase: "Phase 1", target: "Q2", status: "planned" },
  { id: "MS-5", title: "BHARAT EVAL v0.1 authored", phase: "Phase 0", target: "Q2", status: "planned" },
];

export const activity: ActivityEntry[] = [
  { id: "A-1", at: "09:42", actor: "Research lead", entity: "EXP-0007", message: "Experiment configuration drafted" },
  { id: "A-2", at: "08:15", actor: "Research lead", entity: "tok-v0.3", message: "Tokenizer draft published" },
  { id: "A-3", at: "07:03", actor: "Data engineering", entity: "DS-001", message: "Licensing review opened" },
  { id: "A-4", at: "Yesterday", actor: "Evaluation", entity: "BHARAT EVAL", message: "Category list finalised" },
];

export const alerts: Alert[] = [
  { id: "AL-1", severity: "warning", area: "Compute", message: "No compute backend connected — training cannot be executed.", at: "Persistent" },
  { id: "AL-2", severity: "warning", area: "Data", message: "Licensing status unresolved for all candidate corpora.", at: "Persistent" },
  { id: "AL-3", severity: "info", area: "Evaluation", message: "No benchmark scores recorded. Leaderboard intentionally empty.", at: "Persistent" },
];

export const team: TeamMember[] = [
  { id: "U-1", name: "Rajesh", role: "admin", team: "Leadership", focus: "Company + research direction", status: "active" },
  { id: "U-2", name: "Research lead (open)", role: "research_lead", team: "Research", focus: "Architecture + tokenizer", status: "invited" },
  { id: "U-3", name: "Data engineer (open)", role: "data_engineer", team: "Data", focus: "Pipeline + provenance", status: "invited" },
  { id: "U-4", name: "Infrastructure (open)", role: "infra", team: "Infrastructure", focus: "Cluster + training ops", status: "invited" },
  { id: "U-5", name: "Evaluation (open)", role: "researcher", team: "Evaluation", focus: "BHARAT EVAL", status: "invited" },
];

export const auditLog: AuditLogEntry[] = [
  { id: "AU-1", at: "2026-02-18 09:42", actor: "Rajesh", action: "experiment.create", target: "EXP-0007", ip: "—" },
  { id: "AU-2", at: "2026-02-16 11:20", actor: "Rajesh", action: "dataset.update", target: "DS-001", ip: "—" },
  { id: "AU-3", at: "2026-02-14 18:02", actor: "Rajesh", action: "model.register", target: "M-050M", ip: "—" },
];

export const apiKeys: ApiKeyRecord[] = [
  { id: "K-1", label: "Training cluster (planned)", scope: "training:write", createdAt: "—", lastUsed: null, status: "revoked" },
  { id: "K-2", label: "Evaluation harness (planned)", scope: "evaluation:write", createdAt: "—", lastUsed: null, status: "revoked" },
];

export const docs: DocPage[] = [
  { id: "D-1", title: "Control plane overview", section: "Platform", summary: "What this system is and what it is explicitly not.", updatedAt: "2026-02-18" },
  { id: "D-2", title: "Experiment record conventions", section: "Research", summary: "Required fields, immutability rules, naming.", updatedAt: "2026-02-16" },
  { id: "D-3", title: "Dataset provenance policy", section: "Data", summary: "Licensing, PII, contamination and datasheet requirements.", updatedAt: "2026-02-14" },
  { id: "D-4", title: "BHARAT EVAL specification", section: "Evaluation", summary: "Categories, languages, versioning and regression rules.", updatedAt: "2026-02-12" },
  { id: "D-5", title: "Backend service contract", section: "Engineering", summary: "REST surface the control plane expects from ML services.", updatedAt: "2026-02-10" },
  { id: "D-6", title: "Security model", section: "Security", summary: "Roles, access scopes, secrets handling and audit trail.", updatedAt: "2026-02-08" },
];
